<?xml version="1.0" encoding="utf-8"?><Database Name="Wilec DB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;|DataDirectory|\Wilec DB.mdf&quot;;Integrated Security=True" SettingsObjectName="AWilec.Properties.Settings" SettingsPropertyName="Wilec_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contacts" Member="contacts">
    <Type Name="contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cellno" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="altCell" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="business" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Association Name="contact_employee" Member="employees" ThisKey="Id" OtherKey="contact_id" Type="employee" />
    </Type>
  </Table>
  <Table Name="dbo.addresses" Member="addresses">
    <Type Name="address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="address_employee" Member="employees" ThisKey="Id" OtherKey="address_id" Type="employee" />
    </Type>
  </Table>
  <Table Name="dbo.products" Member="products">
    <Type Name="product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proimage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="supplier_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ptype_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="warehouse_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="psw" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="employee_user" Member="employee" ThisKey="employee_id" OtherKey="Id" Type="employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employees" Member="employees">
    <Type Name="employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(90)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(90)" CanBeNull="true" />
      <Column Name="dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contact_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="employee_user" Member="user" ThisKey="Id" OtherKey="employee_id" Type="user" Cardinality="One" />
      <Association Name="address_employee" Member="address" ThisKey="address_id" OtherKey="Id" Type="address" IsForeignKey="true" />
      <Association Name="contact_employee" Member="contact" ThisKey="contact_id" OtherKey="Id" Type="contact" IsForeignKey="true" />
    </Type>
  </Table>
</Database>