//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FirstService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.IloginReg")]
    public interface IloginReg {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/Login", ReplyAction="http://tempuri.org/IloginReg/LoginResponse")]
        bool Login(string usrername, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/Login", ReplyAction="http://tempuri.org/IloginReg/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string usrername, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/Register", ReplyAction="http://tempuri.org/IloginReg/RegisterResponse")]
        string Register(string title, string FN, string surname, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/Register", ReplyAction="http://tempuri.org/IloginReg/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string title, string FN, string surname, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/getAllUsers", ReplyAction="http://tempuri.org/IloginReg/getAllUsersResponse")]
        TestService.LoginService.User[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/getAllUsers", ReplyAction="http://tempuri.org/IloginReg/getAllUsersResponse")]
        System.Threading.Tasks.Task<TestService.LoginService.User[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/getFemaleUsers", ReplyAction="http://tempuri.org/IloginReg/getFemaleUsersResponse")]
        TestService.LoginService.User[] getFemaleUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginReg/getFemaleUsers", ReplyAction="http://tempuri.org/IloginReg/getFemaleUsersResponse")]
        System.Threading.Tasks.Task<TestService.LoginService.User[]> getFemaleUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IloginRegChannel : TestService.LoginService.IloginReg, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IloginRegClient : System.ServiceModel.ClientBase<TestService.LoginService.IloginReg>, TestService.LoginService.IloginReg {
        
        public IloginRegClient() {
        }
        
        public IloginRegClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IloginRegClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginRegClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginRegClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string usrername, string password) {
            return base.Channel.Login(usrername, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string usrername, string password) {
            return base.Channel.LoginAsync(usrername, password);
        }
        
        public string Register(string title, string FN, string surname, string email, string username, string password) {
            return base.Channel.Register(title, FN, surname, email, username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string title, string FN, string surname, string email, string username, string password) {
            return base.Channel.RegisterAsync(title, FN, surname, email, username, password);
        }
        
        public TestService.LoginService.User[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public System.Threading.Tasks.Task<TestService.LoginService.User[]> getAllUsersAsync() {
            return base.Channel.getAllUsersAsync();
        }
        
        public TestService.LoginService.User[] getFemaleUsers() {
            return base.Channel.getFemaleUsers();
        }
        
        public System.Threading.Tasks.Task<TestService.LoginService.User[]> getFemaleUsersAsync() {
            return base.Channel.getFemaleUsersAsync();
        }
    }
}
